import Sidebar from "../components/Sidebar";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import { SessionProvider } from "../components/SessionProvider";
import LoginComponent from "../components/LoginComponent";
import ClientProvider from "../components/ClientProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <LoginComponent />
          ) : (
            <>
              <div className="flex">
                {/* sidebar */}
                <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                  <Sidebar />
                </div>

                <ClientProvider />

                <div className="bg-[#343541] flex-1">{children}</div>
              </div>
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
